---
title: "CRC Engage"
author: "Erich Seamon"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CRC Engage Summary

CRC Engage Summary Statement

```{r echo=FALSE, warning=FALSE, message=FALSE}

library(ggplot2)

crcdata <- read.csv("./data/crc_data_ES2.csv")


#set YN to 01
require(dplyr)
crcdata <- crcdata %>%
  mutate(solution_proposed_YN = ifelse(solution_proposed_YN == "N",0,1))

require(dplyr)
crcdata <- crcdata %>%
  mutate(solution_implemented_YN = ifelse(solution_implemented_YN == "N",0,1))

require(dplyr)
crcdata <- crcdata %>%
  mutate(S_stakeholder_engagment_YN = ifelse(S_stakeholder_engagment_YN == "N",0,1))

#fix colnames
names(crcdata)[names(crcdata) == 'STE_IAP2_NA'] <- 'STE_IAP2_data_gathering'
names(crcdata)[names(crcdata) == 'G_na'] <- 'G_nogeography'

```


```{r echo=FALSE, warning=FALSE, message=FALSE}
ggplot(crcdata,aes(x=solution_proposed_YN, fill=year)) + ggtitle("Solution Proposed: Y=18") +
  geom_bar(stat = "count", position = "dodge", fill="gray", color="black") + theme_minimal()

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

ggplot(crcdata,aes(x=solution_implemented_YN, fill=year)) + ggtitle("Solution Implemented: Y=11") +
  geom_bar(stat = "count", position = "dodge", fill="gray", color="black") + theme_minimal()

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

par(mar = c(8,4,4,4))
barplot(colSums(crcdata[,4:10]), las=2, main="Solution Types: N=18")

```


```{r echo=FALSE, warning=FALSE, message=FALSE}
ggplot(crcdata,aes(x=S_model_YN, fill=year)) + ggtitle("Computational Model Used: Y=366") +
  geom_bar(stat = "count", position = "dodge", fill="gray", color="black") + theme_minimal()
 
``` 


```{r echo=FALSE, warning=FALSE, message=FALSE}

# nrow(subset(crcdata, solution_proposed_YN == "1"))/nrow(subset(crcdata, solution_proposed_YN == "0"))
# 
# nrow(subset(crcdata, solution_implemented_YN == "1"))/nrow(subset(crcdata, solution_implemented_YN == "0"))


#stakeholder
par(mar = c(4,4,4,4))
barplot(table(crcdata$S_stakeholder_engagment_YN), main = "Stakeholder Engagment: N=92")

```


```{r echo=FALSE, warning=FALSE, message=FALSE}
#year
barplot(table(crcdata$year), main="Year")

```

```{r echo=FALSE, warning=FALSE, message=FALSE}
#researcher
df <- t(t(colSums(crcdata[,12:17])))
df <- df[order(df[,1], decreasing = TRUE),]
par(mar = c(6,4,4,4))
barplot(df, las=2, main = "Researcher Types")

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

#stakeholder types
df <- t(t(colSums(crcdata[,23:32])))
df <- df[order(df[,1], decreasing = TRUE),]
par(mar = c(11,4,4,4))
barplot(df, las=2, main = "Stakeholder Types")

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

#ghodsvali scale
df <- t(t(colSums(crcdata[,33:36])))
df <- df[order(df[,1], decreasing = TRUE),]
barplot(df, las=2, main="Ghodsvali Scale Breakdown")

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

#IAP2 scale
df <- t(t(colSums(crcdata[,37:43])))
df <- df[order(df[,1], decreasing = TRUE),]
par(mar = c(12,4,4,4))
barplot(df, las=2, main = "IAP2 Scale Breakdown")

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

#local scale
df <- t(t(colSums(crcdata[,44:51])))
df <- df[order(df[,1], decreasing = TRUE),]
par(mar = c(9,4,4,4))
barplot(df, las=2, main="Local Scale Breakdown")

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

#geography
df <- t(t(colSums(crcdata[,52:57])))
df <- df[order(df[,1], decreasing = TRUE),]
par(mar = c(8,4,4,4))
barplot(df, las=2, main="Geographic Location Breakdown")

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

#Odds of stakeholder scale predicting whether a solution was proposed or not

ghodsvali.fit<-glm(solution_proposed_YN ~STE_G_nominal+STE_G_instrumental+STE_G_representation+STE_G_transformative,family=binomial,data=crcdata)
IAP2.fit<-glm(solution_proposed_YN ~STE_IAP2_data_gathering+STE_IAP2_inform+STE_IAP2_consult+STE_IAP2_involve+STE_IAP2_collab+STE_IAP2_empower+STE_IAP2_researcher,family=binomial,data=crcdata)
IAP2.fit<-glm(solution_proposed_YN ~STE_IAP2_data_gathering+STE_IAP2_inform+STE_IAP2_consult+STE_IAP2_involve+STE_IAP2_collab+STE_IAP2_empower+STE_IAP2_researcher,family=binomial,data=crcdata)
local.fit<-glm(solution_proposed_YN ~SC_datagathering+SC_inform+SC_perspectives+SC_plan+SC_identify+SC_envision+SC_implement+SC_notdescribed,family=binomial,data=crcdata)



```



